[package]
name = "secingest"
version = "0.1.0"
edition = "2021"

[dependencies]
snafu = "0.8.4"

secparser_core = { path = "../secparser_core" }
postgres = "0.19.8"
indicatif = "0.17.8"

log = { workspace = true }
env_logger = { workspace= true }
inquire = "0.7.5"
